project:
  type: book
  output-dir: docs

execute: 
  echo: true
  warning: false
  message: false
  
book:
  title: "C++ for R Users"
  chapters:
    - index.qmd
    - 01-setup.qmd
    - 02-package-skeleton.qmd
    - 03-statistical-functions.qmd
    - 04-logical-functions.qmd
    - 05-rolling-functions.qmd
    - 06-statistical-functions-2.qmd
    - 07-rolling-functions-2.qmd
    - 08-r-packages-expanded.qmd
    - 09-cpp11-rcpp.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo]
    number-sections: false
